### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by Philippevial** [philippe-fredrik/corkdork#51]
We now have the logger implemented but we need to use it in the code aswell.

https://github.com/kappsegla/spring-loppis/blob/main/src/main/java/se/iths/springloppis/exception/GlobalExceptionHandler.java

This is how it looks in the spring-loppis project.  We probably need some more researching on how to use it!

**Comment by ErikssonF** [comment]
From what I remember from the lecture its used when we throw an exception so that we get log files for what happened when the exception was thrown, but we need an implementation of GlobalExceptionHandler with the ControllerAdvice-annotation.
