### ISSUE TITLE
Implement models+mappers

### ISSUE THREAD

**Issue by Philippevial** [philippe-fredrik/corkdork#52]
We need to implement models and mapp them to the entity classes. This is why sonarlint is giving us "Replace this persistent entity with a simple POJO or DTO object." warning on the Requestbody parameters in the controller classes.

https://github.com/kappsegla/spring-loppis/blob/main/src/main/java/se/iths/springloppis/service/ItemService.java

Martin showed us this on friday, the link above is the example.

There is a dependency we can use:

 <dependency>
            <groupId>org.modelmapper</groupId>
            <artifactId>modelmapper</artifactId>
            <version>3.0.0</version>
        </dependency>

**Comment by ErikssonF** [comment]
I rewatched this lecture recently, so I can try to implement this tomorrow!
